import { NextRequest, NextResponse } from 'next/server';
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string; path: string[] } }
) {
  try {
    const supabase = createRouteHandlerClient({ cookies });
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const filePath = '/' + params.path.join('/');

    // Load file from database
    const { data: file, error } = await supabase
      .from('project_files')
      .select('content')
      .eq('workflow_id', params.id)
      .eq('file_path', filePath)
      .single();

    if (error || !file) {
      // Fallback to mock content
      const content = getMockFileContent(filePath);
      return NextResponse.json({ content });
    }

    return NextResponse.json({ content: file.content });
  } catch (error) {
    console.error('Error loading file:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string; path: string[] } }
) {
  try {
    const supabase = createRouteHandlerClient({ cookies });
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { content } = await request.json();
    const filePath = '/' + params.path.join('/');

    // Save file to database
    const { error } = await supabase
      .from('project_files')
      .upsert({
        workflow_id: params.id,
        file_path: filePath,
        content,
        updated_at: new Date().toISOString(),
      }, {
        onConflict: 'workflow_id,file_path'
      });

    if (error) {
      console.error('Error saving file:', error);
      return NextResponse.json(
        { error: 'Failed to save file' },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error saving file:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function getMockFileContent(path: string): string {
  const mockContents: Record<string, string> = {
    '/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to ${path}</h1>
      <p className="mt-4 text-lg text-gray-600">
        Edit this file to get started
      </p>
    </main>
  );
}`,
    '/app/layout.tsx': `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

export const dynamic = 'force-dynamic';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Mr.Prompt',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`,
    '/components/Header.tsx': `export function Header() {
  return (
    <header className="border-b">
      <div className="container mx-auto px-4 py-4">
        <h1 className="text-2xl font-bold">My App</h1>
      </div>
    </header>
  );
}`,
    '/package.json': `{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.0",
    "react": "^18",
    "react-dom": "^18"
  }
}`,
    '/README.md': `# My App

This project was generated by Mr.Prompt.

## Getting Started

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.
`,
  };

  return mockContents[path] || `// File: ${path}\n\n// Content not yet generated`;
}
