/**
 * Agent 3: Database & Backend Developer
 * 
 * รับผิดชอบ:
 * - สร้าง Supabase migrations
 * - สร้าง API routes
 * - สร้าง database functions และ triggers
 * - ตั้งค่า RLS policies
 */

import type { Agent2Output } from './types'

export interface DatabaseTable {
  name: string
  columns: {
    name: string
    type: string
    nullable: boolean
    default?: string
    references?: {
      table: string
      column: string
    }
  }[]
  indexes?: string[]
  policies?: string[]
}

export interface APIRoute {
  path: string
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  description: string
  authentication: boolean
  parameters?: {
    name: string
    type: string
    required: boolean
  }[]
  response: string
}

export interface Agent3Output {
  migrations: {
    filename: string
    sql: string
    description: string
  }[]
  api_routes: {
    path: string
    filename: string
    code: string
  }[]
  database_functions: {
    name: string
    sql: string
    description: string
  }[]
  rls_policies: {
    table: string
    policy_name: string
    sql: string
  }[]
  validation_schemas: {
    name: string
    schema: Record<string, any>
  }[]
}

/**
 * Execute Agent 3: Database & Backend Development
 */
export async function executeAgent3(
  architecture: Agent2Output
): Promise<Agent3Output> {
  console.log('[Agent 3] Starting Database & Backend Development...')
  
  try {
    // 1. วิเคราะห์และสร้าง database migrations
    const migrations = await generateMigrations(architecture)
    
    // 2. สร้าง API routes
    const apiRoutes = await generateAPIRoutes(architecture)
    
    // 3. สร้าง database functions
    const databaseFunctions = await generateDatabaseFunctions(architecture)
    
    // 4. สร้าง RLS policies
    const rlsPolicies = await generateRLSPolicies(architecture)
    
    // 5. สร้าง validation schemas
    const validationSchemas = await generateValidationSchemas(architecture)
    
    console.log('[Agent 3] Database & Backend Development completed successfully')
    
    return {
      migrations,
      api_routes: apiRoutes,
      database_functions: databaseFunctions,
      rls_policies: rlsPolicies,
      validation_schemas: validationSchemas
    }
  } catch (error) {
    console.error('[Agent 3] Error:', error)
    throw new Error(`Agent 3 failed: ${error instanceof Error ? error.message : String(error)}`)
  }
}

/**
 * Generate database migrations from architecture
 */
async function generateMigrations(architecture: Agent2Output) {
  const migrations: Agent3Output['migrations'] = []
  
  // TODO: Implement actual migration generation using AI or templates
  // For now, return example structure
  
  const timestamp = Date.now()
  const migrationNumber = String(timestamp).slice(-3)
  
  migrations.push({
    filename: `${migrationNumber}_create_tables.sql`,
    sql: `-- Migration: Create tables
-- Generated by Agent 3

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create tables
-- TODO: Generate actual table definitions from architecture.database_schema

-- Example:
-- CREATE TABLE IF NOT EXISTS example_table (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   name TEXT NOT NULL,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
`,
    description: 'Create initial database tables'
  })
  
  return migrations
}

/**
 * Generate API routes from architecture
 */
async function generateAPIRoutes(architecture: Agent2Output) {
  const routes: Agent3Output['api_routes'] = []
  
  // TODO: Implement actual API route generation
  // For now, return example structure
  
  routes.push({
    path: '/api/example',
    filename: 'app/api/example/route.ts',
    code: `import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

export async function GET(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  // Get session
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  
  // Fetch data
  const { data, error } = await supabase
    .from('example_table')
    .select('*')
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ data })
}

export async function POST(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  // Get session
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  
  // Parse body
  const body = await request.json()
  
  // Validate
  // TODO: Add validation
  
  // Insert data
  const { data, error } = await supabase
    .from('example_table')
    .insert(body)
    .select()
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ data }, { status: 201 })
}
`
  })
  
  return routes
}

/**
 * Generate database functions
 */
async function generateDatabaseFunctions(architecture: Agent2Output) {
  const functions: Agent3Output['database_functions'] = []
  
  // TODO: Implement actual function generation
  
  functions.push({
    name: 'update_updated_at',
    sql: `CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';`,
    description: 'Automatically update updated_at timestamp'
  })
  
  return functions
}

/**
 * Generate RLS policies
 */
async function generateRLSPolicies(architecture: Agent2Output) {
  const policies: Agent3Output['rls_policies'] = []
  
  // TODO: Implement actual policy generation
  
  policies.push({
    table: 'example_table',
    policy_name: 'Users can view their own data',
    sql: `CREATE POLICY "Users can view their own data" 
  ON example_table FOR SELECT 
  USING (auth.uid() = user_id);`
  })
  
  return policies
}

/**
 * Generate validation schemas
 */
async function generateValidationSchemas(architecture: Agent2Output) {
  const schemas: Agent3Output['validation_schemas'] = []
  
  // TODO: Implement actual schema generation using Zod or similar
  
  schemas.push({
    name: 'ExampleSchema',
    schema: {
      name: { type: 'string', required: true, minLength: 1 },
      email: { type: 'string', required: true, format: 'email' },
      age: { type: 'number', required: false, min: 0, max: 150 }
    }
  })
  
  return schemas
}

/**
 * Helper: Generate CRUD API route code
 */
export function generateCRUDRoute(options: {
  entity: string
  table: string
  authentication: boolean
  operations: ('create' | 'read' | 'update' | 'delete')[]
}): string {
  const { entity, table, authentication, operations } = options
  
  let code = `import { NextRequest, NextResponse } from 'next/server'
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

`
  
  // GET (Read)
  if (operations.includes('read')) {
    code += `export async function GET(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  ${authentication ? `
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  ` : ''}
  
  const { data, error } = await supabase
    .from('${table}')
    .select('*')
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ data })
}

`
  }
  
  // POST (Create)
  if (operations.includes('create')) {
    code += `export async function POST(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  ${authentication ? `
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  ` : ''}
  
  const body = await request.json()
  
  const { data, error } = await supabase
    .from('${table}')
    .insert(body)
    .select()
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ data }, { status: 201 })
}

`
  }
  
  // PUT (Update)
  if (operations.includes('update')) {
    code += `export async function PUT(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  ${authentication ? `
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  ` : ''}
  
  const body = await request.json()
  const { id, ...updates } = body
  
  if (!id) {
    return NextResponse.json({ error: 'ID is required' }, { status: 400 })
  }
  
  const { data, error } = await supabase
    .from('${table}')
    .update(updates)
    .eq('id', id)
    .select()
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ data })
}

`
  }
  
  // DELETE
  if (operations.includes('delete')) {
    code += `export async function DELETE(request: NextRequest) {
  const supabase = createRouteHandlerClient({ cookies })
  
  ${authentication ? `
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  ` : ''}
  
  const { searchParams } = new URL(request.url)
  const id = searchParams.get('id')
  
  if (!id) {
    return NextResponse.json({ error: 'ID is required' }, { status: 400 })
  }
  
  const { error } = await supabase
    .from('${table}')
    .delete()
    .eq('id', id)
  
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  
  return NextResponse.json({ success: true })
}
`
  }
  
  return code
}
